[toolchain]
channel = "1.88.0"
profile = "default" # include rustfmt, clippy
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-src",
    "rust-std",
    "rustc",
    "rustfmt",
]
targets = ["wasm32-unknown-unknown"]
